# Generated by Django 4.1.4 on 2022-12-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lion',
            old_name='descriptions',
            new_name='description',
        ),
    ]
